import Head from 'next/head'
import { Categories, PostCard, PostWidget, AboutMe } from '../components'
import { getPosts } from '../services'

import FeaturedPosts from '../sections/FeaturedPosts'

export default function Home ({ posts }) {
  return (
    <div className='container mx-auto px-10 mb-8'>
      <Head>
        <title>Ziyodullo Rakhmonberdiev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FeaturedPosts />
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-4 col-span-1'>
          <div className='relative'>
            <PostWidget />
          </div>
          <div className='relative'>
            <AboutMe />
          </div>
          <div className='relative lg:sticky top-8'>
            <Categories />
          </div>
        </div>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, index) => (
            <PostCard post={post.node} key={index} />
          ))}
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps () {
  const posts = (await getPosts()) || []

  return {
    props: { posts }
  }
}
